
version: '3.4'

services:
  todoapi:
    image: todoapi
    build:
      context: .
      dockerfile: src/TodoTaskManagement.API/Dockerfile
    container_name: todoapi
    ports: 
      - "5000:80"
    depends_on:
      - sqlserver
  
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlserver
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#p@55w0rd# 
